from __future__ import annotations

import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
APPENDIX_DIR = ROOT / "outputs" / "appendix"
HEAD_METHOD = APPENDIX_DIR / "head_method.md"
FIGURE = APPENDIX_DIR / "figure.md"
TABLE_TEMP = APPENDIX_DIR / "table_temp.md"
REFERENCES = APPENDIX_DIR / "references.md"
FINAL = APPENDIX_DIR / "Supplementary Material.md"

METHODS_HEADING = "## eMethods"
LEGACY_METHODS_HEADING = "## Materials and Methods"
TABLES_HEADING = "## eTables"
REFERENCES_HEADING = "## References"
FIGURES_HEADING = "## eFigures"
SUPPLEMENT_TITLE = (
    "Optimization of Infant Pertussis Prevention and "
    "Resistance-Management Strategies"
)

SECTION_HEADING_RE = re.compile(r"(?m)^## ")
TABLE_START_RE = re.compile(r"(?m)^(?:###\s+eTable \d+\.|\*\*(?:eTable \d+|Table S\d+)\.)")
TABLE_GENERATOR_COMMENT_RE = re.compile(
    r"(?m)^<!-- (?:BEGIN|END) (?:E?TABLE S?\d+|TABLE S?\d+) -->\n?"
    r"|^<!-- Generated by `manuscript_notes/render_supplementary_tables.py`; do not edit inside this block\. -->\n?"
)
APPENDIX_LINK_RE = re.compile(r"(?<=\]\()outputs/appendix/")
INLINE_MATH_RE = re.compile(r"\\\((.+?)\\\)", re.DOTALL)
PAGE_BREAK = '<div style="page-break-after: always;"></div>'
PAGE_BREAK_RE = re.compile(
    r"\n*<div\s+style=[\"']page-break-after:\s*always;[\"']>\s*</div>\n*",
    re.IGNORECASE,
)
EFIGURE_IMAGE_RE = re.compile(r"(?m)^!\[eFigure \d+\]\([^)]+\)")
EFIGURE_TITLE_RE = re.compile(r"(?ms)^\*\*(eFigure \d+\. .*?)\*\*\s*(.*)$")


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text.rstrip() + "\n", encoding="utf-8")


def join_sections(*parts: str) -> str:
    return "\n\n".join(part.strip() for part in parts if part and part.strip())


def normalize_jama_labels(text: str) -> str:
    text = text.replace(
        "Scenario Projections of Infant Pertussis Burden With Vaccine Transmission Blocking and Macrolide Resistance",
        SUPPLEMENT_TITLE,
    )
    text = text.replace(
        "Modeled Infant Pertussis Outcomes Across Vaccination, Exposure-Reduction, "
        "and Resistance-Management Scenarios: A Decision Analytical Modeling Study",
        SUPPLEMENT_TITLE,
    )
    text = text.replace(
        "Infant Pertussis Outcomes Across Prevention and Resistance-Management Scenarios",
        SUPPLEMENT_TITLE,
    )
    text = text.replace("Supplementary Materials", "Supplementary Material")
    text = text.replace(LEGACY_METHODS_HEADING, METHODS_HEADING)
    text = text.replace("## Supplementary figures", FIGURES_HEADING)
    text = text.replace("## Supplementary tables", TABLES_HEADING)
    text = re.sub(r"\bExtended Data Figure (\d+)\b", r"eFigure \1", text)
    text = re.sub(r"\bFig\. S(\d+)\b", r"eFigure \1", text)
    text = re.sub(r"\bFigure S(\d+)\b", r"eFigure \1", text)
    text = re.sub(r"\bTable S(\d+)\b", r"eTable \1", text)
    return text


def normalize_inline_math(text: str) -> str:
    """Use dollar-delimited inline math for markdown renderers.

    Some markdown previews used by collaborators render display math blocks but
    do not render LaTeX inline delimiters written as ``\\(...\\)``. The source
    methods text only uses these delimiters for inline formulas, so this
    normalization keeps display equations unchanged while making inline math
    more portable.
    """
    return INLINE_MATH_RE.sub(lambda match: f"${match.group(1)}$", text)


def extract_section(text: str, heading: str) -> str:
    start = text.index(heading)
    next_heading = SECTION_HEADING_RE.search(text, start + len(heading))
    end = next_heading.start() if next_heading else len(text)
    return text[start:end].rstrip()


def extract_intro(text: str) -> str:
    return text[: text.index(METHODS_HEADING)].rstrip()


def extract_element_titles(text: str, heading_prefix: str) -> list[str]:
    return [
        match.group(1).strip()
        for match in re.finditer(rf"(?m)^###\s+({re.escape(heading_prefix)} \d+\..*)$", text)
    ]


def build_contents_lines(source_text: str) -> list[str]:
    figure_lines = extract_element_titles(source_text, "eFigure")
    table_lines = extract_element_titles(source_text, "eTable")
    return [
        "eMethods. Model equations, country-profile construction, calibration, scenario definitions, uncertainty evaluation, and interpretation limits.",
        *figure_lines,
        *table_lines,
        "eReferences. Supplemental references.",
    ]


def reorder_contents_block(intro: str, source_text: str) -> str:
    marker = "## Contents"
    if marker not in intro:
        return intro.rstrip()

    prefix, _contents_tail = intro.split(marker, 1)
    ordered = build_contents_lines(source_text)
    if not ordered:
        return intro.rstrip()

    rebuilt = "\n".join(f"- {line}" for line in ordered)
    return f"{prefix.rstrip()}\n\n{marker}\n\n{rebuilt}"


def rewrite_appendix_links(text: str) -> str:
    return APPENDIX_LINK_RE.sub("", text)


def normalize_table_section(section: str) -> str:
    section = section.strip()
    if not section:
        return section
    if not section.startswith(TABLES_HEADING):
        return section

    body = section[len(TABLES_HEADING) :].strip()
    body = TABLE_GENERATOR_COMMENT_RE.sub("", body)
    body = PAGE_BREAK_RE.sub("\n\n", body).strip()
    starts = [match.start() for match in TABLE_START_RE.finditer(body)]
    if not starts:
        return section

    starts.append(len(body))
    blocks = [body[starts[i] : starts[i + 1]].strip() for i in range(len(starts) - 1)]
    blocks = [block for block in blocks if block]

    separator = f"\n\n{PAGE_BREAK}\n\n"
    return f"{TABLES_HEADING}\n\n" + separator.join(blocks) + f"\n\n{PAGE_BREAK}"


def normalize_figure_block(block: str) -> str:
    block = block.strip()
    if not block:
        return block

    image_match = EFIGURE_IMAGE_RE.search(block)
    heading_match = re.search(r"(?m)^###\s+(eFigure \d+\..*)$", block)
    title_match = EFIGURE_TITLE_RE.search(block)
    if not image_match or not (heading_match or title_match):
        return block

    image = image_match.group(0).strip()
    if heading_match:
        title = heading_match.group(1).strip()
        caption = block
        for matched in (image_match.group(0), heading_match.group(0)):
            caption = caption.replace(matched, "", 1)
        caption = caption.strip()
    else:
        title = title_match.group(1).strip()
        caption = title_match.group(2).strip()

    parts = [image, f"### {title}"]
    if caption:
        parts.append(caption)
    return "\n\n".join(parts)


def normalize_figure_section(section: str) -> str:
    section = section.strip()
    if not section:
        return section
    if not section.startswith(FIGURES_HEADING):
        return section

    body = section[len(FIGURES_HEADING) :].strip()
    blocks = [block.strip() for block in PAGE_BREAK_RE.split(body) if block.strip()]
    if not blocks:
        return section
    blocks = [normalize_figure_block(block) for block in blocks]
    blocks = [block for block in blocks if block]
    separator = f"\n\n{PAGE_BREAK}\n\n"
    return f"{FIGURES_HEADING}\n\n" + separator.join(blocks) + f"\n\n{PAGE_BREAK}"


def build_fragments(source_text: str) -> tuple[str, str, str, str]:
    source_text = normalize_jama_labels(source_text)
    intro = reorder_contents_block(extract_intro(source_text), source_text)
    methods = extract_section(source_text, METHODS_HEADING)
    references = extract_section(source_text, REFERENCES_HEADING)
    figures = normalize_figure_section(rewrite_appendix_links(extract_section(source_text, FIGURES_HEADING)))
    tables = normalize_table_section(extract_section(source_text, TABLES_HEADING))
    head_method = join_sections(intro, methods)
    return head_method, figures, tables, references


def ensure_fragments(source_text: str) -> None:
    head_method, figure, table_temp, references = build_fragments(source_text)
    write_text(HEAD_METHOD, head_method)
    write_text(FIGURE, figure)
    write_text(TABLE_TEMP, table_temp)
    write_text(REFERENCES, references)


def merge_fragments() -> str:
    head_method = read_text(HEAD_METHOD).strip()
    figure = normalize_figure_section(read_text(FIGURE))
    table_temp = normalize_table_section(read_text(TABLE_TEMP))
    references = read_text(REFERENCES).strip()
    merged = join_sections(head_method, figure, table_temp, references)
    return rewrite_appendix_links(merged) + "\n"


def main() -> None:
    if not all(path.exists() for path in (HEAD_METHOD, FIGURE, TABLE_TEMP, REFERENCES)):
        if not FINAL.exists():
            raise FileNotFoundError(f"Missing supplementary material document: {FINAL}")
        source_text = normalize_jama_labels(read_text(FINAL))
    else:
        source_text = join_sections(
            read_text(HEAD_METHOD),
            read_text(FIGURE),
            read_text(TABLE_TEMP),
            read_text(REFERENCES),
        )

    ensure_fragments(normalize_jama_labels(source_text))
    merged = merge_fragments()
    merged = normalize_inline_math(normalize_jama_labels(merged))
    write_text(FINAL, merged)


if __name__ == "__main__":
    main()
