from __future__ import annotations

import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
APPENDIX_DIR = ROOT / "outputs" / "appendix"
HEAD_METHOD = APPENDIX_DIR / "head_method.md"
FIGURE = APPENDIX_DIR / "figure.md"
TABLE_TEMP = APPENDIX_DIR / "table_temp.md"
REFERENCES = APPENDIX_DIR / "references.md"
FINAL = APPENDIX_DIR / "Supplementary Material.md"

METHODS_HEADING = "## Materials and Methods"
TABLES_HEADING = "## eTables"
REFERENCES_HEADING = "## References"
FIGURES_HEADING = "## eFigures"

SECTION_HEADING_RE = re.compile(r"(?m)^## ")
TABLE_BLOCK_RE = re.compile(
    r"(?ms)^(?:<!-- BEGIN (?:E?TABLE S?\d+) -->\n)?\*\*(?:eTable \d+|Table S\d+)\..*?"
    r"(?:\n<!-- END (?:E?TABLE S?\d+) -->)?"
    r"(?=\n\n(?:<!-- BEGIN (?:E?TABLE S?\d+) -->\n)?\*\*(?:eTable \d+|Table S\d+)\.|\Z)"
)
TABLE_GENERATOR_COMMENT_RE = re.compile(
    r"(?m)^<!-- (?:BEGIN|END) (?:E?TABLE S?\d+|TABLE S?\d+) -->\n?"
    r"|^<!-- Generated by `manuscript_notes/render_supplementary_tables.py`; do not edit inside this block\. -->\n?"
)
APPENDIX_LINK_RE = re.compile(r"(?<=\]\()outputs/appendix/")
INLINE_MATH_RE = re.compile(r"\\\((.+?)\\\)", re.DOTALL)
PAGE_BREAK = '<div style="page-break-after: always;"></div>'
PAGE_BREAK_RE = re.compile(
    r"\n*<div\s+style=[\"']page-break-after:\s*always;[\"']>\s*</div>\n*",
    re.IGNORECASE,
)


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text.rstrip() + "\n", encoding="utf-8")


def join_sections(*parts: str) -> str:
    return "\n\n".join(part.strip() for part in parts if part and part.strip())


def normalize_jama_labels(text: str) -> str:
    text = text.replace("## Supplementary figures", FIGURES_HEADING)
    text = text.replace("## Supplementary tables", TABLES_HEADING)
    text = re.sub(r"\bExtended Data Figure (\d+)\b", r"eFigure \1", text)
    text = re.sub(r"\bFig\. S(\d+)\b", r"eFigure \1", text)
    text = re.sub(r"\bFigure S(\d+)\b", r"eFigure \1", text)
    text = re.sub(r"\bTable S(\d+)\b", r"eTable \1", text)
    return text


def normalize_inline_math(text: str) -> str:
    """Use dollar-delimited inline math for markdown renderers.

    Some markdown previews used by collaborators render display math blocks but
    do not render LaTeX inline delimiters written as ``\\(...\\)``. The source
    methods text only uses these delimiters for inline formulas, so this
    normalization keeps display equations unchanged while making inline math
    more portable.
    """
    return INLINE_MATH_RE.sub(lambda match: f"${match.group(1)}$", text)


def extract_section(text: str, heading: str) -> str:
    start = text.index(heading)
    next_heading = SECTION_HEADING_RE.search(text, start + len(heading))
    end = next_heading.start() if next_heading else len(text)
    return text[start:end].rstrip()


def extract_intro(text: str) -> str:
    return text[: text.index(METHODS_HEADING)].rstrip()


def reorder_contents_block(intro: str) -> str:
    marker = "## Contents"
    if marker not in intro:
        return intro.rstrip()

    prefix, contents_tail = intro.split(marker, 1)
    lines = [line.strip() for line in contents_tail.splitlines() if line.strip()]
    if not lines:
        return intro.rstrip()

    method_line = next((line for line in lines if line.startswith("Materials and Methods")), "Materials and Methods.")
    reference_line = next((line for line in lines if line.startswith("References.")), "References.")
    figure_lines = [line for line in lines if line.startswith(("Fig. ", "eFigure"))] or ["eFigures."]
    table_lines = [line for line in lines if line.startswith(("Table ", "eTable"))] or ["eTables."]
    ordered = [line for line in (method_line, *figure_lines, *table_lines, reference_line) if line]
    if not ordered:
        return intro.rstrip()

    rebuilt = "\n\n".join(ordered)
    return f"{prefix.rstrip()}\n\n{marker}\n\n{rebuilt}"


def rewrite_appendix_links(text: str) -> str:
    return APPENDIX_LINK_RE.sub("", text)


def normalize_table_section(section: str) -> str:
    section = section.strip()
    if not section:
        return section
    if not section.startswith(TABLES_HEADING):
        return section

    body = section[len(TABLES_HEADING) :].strip()
    body = TABLE_GENERATOR_COMMENT_RE.sub("", body)
    body = PAGE_BREAK_RE.sub("\n\n", body).strip()
    blocks = [block.strip() for block in TABLE_BLOCK_RE.findall(body)]
    if not blocks:
        return section

    separator = f"\n\n{PAGE_BREAK}\n\n"
    return f"{TABLES_HEADING}\n\n" + separator.join(blocks) + f"\n\n{PAGE_BREAK}"


def normalize_figure_section(section: str) -> str:
    section = section.strip()
    if not section:
        return section
    if not section.startswith(FIGURES_HEADING):
        return section

    body = section[len(FIGURES_HEADING) :].strip()
    body = PAGE_BREAK_RE.sub("\n\n", body).strip()
    starts = [match.start() for match in re.finditer(r"(?m)^!\[eFigure \d+\]", body)]
    if not starts:
        return section

    starts.append(len(body))
    blocks = [body[starts[i] : starts[i + 1]].strip() for i in range(len(starts) - 1)]
    blocks = [block for block in blocks if block]
    separator = f"\n\n{PAGE_BREAK}\n\n"
    return f"{FIGURES_HEADING}\n\n" + separator.join(blocks) + f"\n\n{PAGE_BREAK}"


def build_fragments(source_text: str) -> tuple[str, str, str, str]:
    intro = reorder_contents_block(extract_intro(source_text))
    methods = extract_section(source_text, METHODS_HEADING)
    references = extract_section(source_text, REFERENCES_HEADING)
    figures = normalize_figure_section(rewrite_appendix_links(extract_section(source_text, FIGURES_HEADING)))
    tables = normalize_table_section(extract_section(source_text, TABLES_HEADING))
    head_method = join_sections(intro, methods)
    return head_method, figures, tables, references


def ensure_fragments(source_text: str) -> None:
    head_method, figure, table_temp, references = build_fragments(source_text)
    write_text(HEAD_METHOD, head_method)
    write_text(FIGURE, figure)
    write_text(TABLE_TEMP, table_temp)
    write_text(REFERENCES, references)


def merge_fragments() -> str:
    head_method = read_text(HEAD_METHOD).strip()
    figure = normalize_figure_section(read_text(FIGURE))
    table_temp = normalize_table_section(read_text(TABLE_TEMP))
    references = read_text(REFERENCES).strip()
    merged = join_sections(head_method, figure, table_temp, references)
    return rewrite_appendix_links(merged) + "\n"


def main() -> None:
    if not all(path.exists() for path in (HEAD_METHOD, FIGURE, TABLE_TEMP, REFERENCES)):
        if not FINAL.exists():
            raise FileNotFoundError(f"Missing supplementary material document: {FINAL}")
        source_text = normalize_jama_labels(read_text(FINAL))
        ensure_fragments(source_text)

    merged = merge_fragments()
    merged = normalize_inline_math(normalize_jama_labels(merged))
    write_text(FINAL, merged)


if __name__ == "__main__":
    main()
