args <- commandArgs(FALSE)
file_arg <- sub("^--file=", "", args[grepl("^--file=", args)])
script_dir <- if (length(file_arg) > 0) dirname(normalizePath(file_arg[[1]])) else file.path(getwd(), "scripts_R")
source(file.path(script_dir, "15_extended_data_1_country_inputs.R"))
source(file.path(script_dir, "16_extended_data_2_diagnostics_sensitivity.R"))
source(file.path(script_dir, "25_extended_data_11_model_structure.R"))
source(file.path(script_dir, "20_extended_data_6_baseline_dynamics.R"))
source(file.path(script_dir, "21_extended_data_7_vaccine_deep_dive.R"))
source(file.path(script_dir, "22_extended_data_8_resistance_dynamics.R"))
source(file.path(script_dir, "24_extended_data_10_intervention_extended.R"))
tryCatch(source(file.path(script_dir, "26_extended_data_13_resistance_hindcast.R")), error = function(e) message("Skipping eFigure 8: ", conditionMessage(e)))
