args <- commandArgs(FALSE)
file_arg <- sub("^--file=", "", args[grepl("^--file=", args)])
script_dir <- if (length(file_arg) > 0) dirname(normalizePath(file_arg[[1]])) else file.path(getwd(), "scripts_R")
source(file.path(script_dir, "15_plot_nature_extended_data_1_country_inputs.R"))
source(file.path(script_dir, "16_plot_nature_extended_data_2_diagnostics_sensitivity.R"))
source(file.path(script_dir, "17_plot_nature_extended_data_3_data_provenance.R"))
source(file.path(script_dir, "18_plot_nature_extended_data_4_calibration_diagnostics.R"))
source(file.path(script_dir, "19_plot_nature_extended_data_5_model_architecture.R"))
source(file.path(script_dir, "20_plot_nature_extended_data_6_baseline_dynamics.R"))
source(file.path(script_dir, "21_plot_nature_extended_data_7_vaccine_deep_dive.R"))
source(file.path(script_dir, "22_plot_nature_extended_data_8_resistance_dynamics.R"))
source(file.path(script_dir, "23_plot_nature_extended_data_9_full_grid.R"))
source(file.path(script_dir, "24_plot_nature_extended_data_10_intervention_extended.R"))
source(file.path(script_dir, "25_plot_nature_extended_data_11_model_structure.R"))
source(file.path(script_dir, "26_plot_nature_extended_data_12_contact_matrix_reconstruction.R"))
