args <- commandArgs(FALSE)
file_arg <- sub("^--file=", "", args[grepl("^--file=", args)])
script_dir <- if (length(file_arg) > 0) dirname(normalizePath(file_arg[[1]])) else file.path(getwd(), "scripts_R")
source(file.path(script_dir, "11_plot_nature_figure_1_baseline_heterogeneity.R"))
source(file.path(script_dir, "12_plot_nature_figure_2_vaccine_mechanisms.R"))
source(file.path(script_dir, "13_plot_nature_figure_3_resistance_interaction.R"))
source(file.path(script_dir, "14_plot_nature_figure_4_intervention_prioritisation.R"))
